/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CofreRouteImport } from './routes/cofre'
import { Route as IndexRouteImport } from './routes/index'

const CofreRoute = CofreRouteImport.update({
  id: '/cofre',
  path: '/cofre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cofre': typeof CofreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cofre': typeof CofreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cofre': typeof CofreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cofre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cofre'
  id: '__root__' | '/' | '/cofre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CofreRoute: typeof CofreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cofre': {
      id: '/cofre'
      path: '/cofre'
      fullPath: '/cofre'
      preLoaderRoute: typeof CofreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CofreRoute: CofreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
