/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MidiaRouteImport } from './routes/midia'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as CofreRouteImport } from './routes/cofre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizacaoNotasRouteImport } from './routes/organizacao.notas'

const MidiaRoute = MidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const CofreRoute = CofreRouteImport.update({
  id: '/cofre',
  path: '/cofre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacaoNotasRoute = OrganizacaoNotasRouteImport.update({
  id: '/organizacao/notas',
  path: '/organizacao/notas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cofre': typeof CofreRoute
  '/financas': typeof FinancasRoute
  '/midia': typeof MidiaRoute
  '/organizacao/notas': typeof OrganizacaoNotasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cofre': typeof CofreRoute
  '/financas': typeof FinancasRoute
  '/midia': typeof MidiaRoute
  '/organizacao/notas': typeof OrganizacaoNotasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cofre': typeof CofreRoute
  '/financas': typeof FinancasRoute
  '/midia': typeof MidiaRoute
  '/organizacao/notas': typeof OrganizacaoNotasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cofre' | '/financas' | '/midia' | '/organizacao/notas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cofre' | '/financas' | '/midia' | '/organizacao/notas'
  id:
    | '__root__'
    | '/'
    | '/cofre'
    | '/financas'
    | '/midia'
    | '/organizacao/notas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CofreRoute: typeof CofreRoute
  FinancasRoute: typeof FinancasRoute
  MidiaRoute: typeof MidiaRoute
  OrganizacaoNotasRoute: typeof OrganizacaoNotasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/midia': {
      id: '/midia'
      path: '/midia'
      fullPath: '/midia'
      preLoaderRoute: typeof MidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cofre': {
      id: '/cofre'
      path: '/cofre'
      fullPath: '/cofre'
      preLoaderRoute: typeof CofreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacao/notas': {
      id: '/organizacao/notas'
      path: '/organizacao/notas'
      fullPath: '/organizacao/notas'
      preLoaderRoute: typeof OrganizacaoNotasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CofreRoute: CofreRoute,
  FinancasRoute: FinancasRoute,
  MidiaRoute: MidiaRoute,
  OrganizacaoNotasRoute: OrganizacaoNotasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
