services:
  postgres:
    image: postgres:17-alpine
    container_name: los-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: los
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
